### ISSUE TITLE
Please close this repo

### ISSUE THREAD

**Issue by AustinG292** [haraldh/iconsole-android#10]
We are iConsole and this protocol is not an open open. All customers or developers who would like to develop apps that interact with iConsole MUST sign a None Disclosure Agreement first.

**Comment by haraldh** [comment]
You cannot stop me doing this. I found out about the protocol by my own.

**Comment by AustinG292** [comment]
This is NOT an open protocol unless you have agreement with our end. Have you signed a NDA with us?

Austin

**Comment by haraldh** [comment]
I have reverse engineered the protocol by using the android feature of capturing the Bluetooth communication. No NDA needed and totally legal in my country.

**Comment by AustinG292** [comment]
Using someone’s IP without any agreement is legal. Lovely. Please tell which country you are from. I will share to the IP takers and they might interest in moving there.

**Comment by haraldh** [comment]
In Germany analysis and reverse engineering of protocols is totally legal.
