### ISSUE TITLE
Can't build in Android Studio

### ISSUE THREAD

**Issue by Netapilius** [haraldh/iconsole-android#4]
I tried to build the project and it complains that it can't find android_antlib_4-14-0.jar
When I add that file to the android_antlib_4-14 folder. I get another error: Program type already present: com.dsi.ant.channel.PredefinedNetwork. Since this enum is already declared in the jar library (without the ANT_PLUS_1 value)
So how do I build this?

BR,
Frederic

**Comment by haraldh** [comment]
try the `no-ant` branch

If you want to build with ant, you have to remove `com/dsi/ant/channel/PredefinedNetwork.class` from the `android_antlib_4-14-0.jar`

**Comment by Netapilius** [comment]
Perfect! Removing class from the jar-file did the trick (I didn't know it was that simple: just change the extension to zip and remove the class file, and change it back to jar). Thanks! I'm going to play around a little with this project for my crosstrainer. Thanks for the effort of putting this together!

**Comment by Mindblower909** [comment]
Dear,
I’m not a coder but very interested in transforming my iConsole+ fitness bike into an ANT compatible device in order to link my Garmin or smartphone through Strava to record all metrics like watt, RPM etc

Can you help me?

Thanks, Yves
